# Use with https://keymap-drawer.streamlit.app
layout: {zmk_keyboard: cradio}
layers:
  default:
  - {t: Q, right: "^"}
  - {t: C, right: "<"}
  - {t: O, right: ">"}
  - {t: P, right: "$"}
  - {t: W, right: "%"}
  - {t: J, right: "@"}
  - {t: M, right: "&"}
  - {t: D, right: "*"}
  - {t: "★", s: "!", right: "'"}
  - {t: Y, right: "`"}
  - {t: A, h: "shift", right: "{"}
  - {t: S, h: "gui", right: "("}
  - {t: E, h: "ctrl", right: ")"}
  - {t: N, h: "alt", right: "}"}
  - {t: F, right: "="}
  - {t: L, right: "\\"}
  - {t: R, h: "alt", right: "+"}
  - {t: T, h: "ctrl", right: "-"}
  - {t: I, h: "gui", right: "/"}
  - {t: U, h: "shift", right: '"'}
  - {t: Z, right: "~"}
  - {t: X, h: alt gr, right: "["}
  - {t: "-", s: "?", right: "]"}
  - {t: V, right: "_"}
  - {t: B, right: "#"}
  - {t: ".", s: ":", right: "|"}
  - {t: H, right: "!"}
  - {t: G, right: ";"}
  - {t: ",", h: alt gr, s: ";", right: ":"}
  - {t: K, right: "?"}
  - {t: ⎋, h: shift}
  - {t: ⌫, h: left}
  - {t: ␣, h: right}
  - {t: ↩, h: alt gr}
  right:
  - ''
  - "⇱"
  - "↑"
  - "⇲"
  - "⇞"
  - "/"
  - '7'
  - '8'
  - '9'
  - ''
  - {t: "↹", h: "shift"}
  - {t: "←", h: "gui"}
  - {t: "↓", h: "ctrl"}
  - {t: "→", h: "alt"}
  - "⇟"
  - "-"
  - {t: '4', h: "alt"}
  - {t: '5', h: "ctrl"}
  - {t: '6', h: "gui"}
  - {t: '0', h: "shift"}
  - ''
  - VOL-
  - MUTE
  - VOL+
  - ''
  - ","
  - '1'
  - '2'
  - '3'
  - "."
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  left:
  - ''
  - ''
  - ''
  - ''
  - '⌦'
  - ''
  - F7
  - F8
  - F9
  - F10
  - {t: ↹, h: "shift"}
  - {t: ↹, h: "gui"}
  - {t: ↹, h: "ctrl"}
  - {t: ↹, h: "alt"}
  - ctrl+R
  - ''
  - {t: F4, h: "alt"}
  - {t: F5, h: "ctrl"}
  - {t: F6, h: "gui"}
  - {t: F11, h: "shift"}
  - "⇧⇧"
  - webex all
  - webex unread
  - prnt scrn
  - ctrl+T
  - ''
  - F1
  - F2
  - F3
  - F12
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  tri:
  - '&sys_reset'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - BT 0
  - BT 3
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&sys_reset'
  - '&bootloader'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - BT 1
  - BT 4
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&bootloader'
  - '&studio_unlock'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - BT CLR
  - BT 2
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&studio_unlock'
  - {t: ▽, type: trans}
  - {type: held}
  - {type: held}
  - {t: ▽, type: trans}
