# Use with https://keymap-drawer.streamlit.app
layout: {zmk_keyboard: cradio}
layers:
  default:
  - {t: Q, right: "^"}
  - {t: C, right: "<"}
  - {t: O, right: ">"}
  - {t: P, right: "$"}
  - {t: W, right: "%"}
  - {t: J, right: "@"}
  - {t: M, right: "&"}
  - {t: D, right: "*"}
  - {t: "★", s: "!", right: "'"}
  - {t: Y, right: "`"}
  - {t: A, h: "⇧", right: "{"}
  - {t: S, h: "⌥", right: "("}
  - {t: E, h: "⌘", right: ")"}
  - {t: N, h: "⌃", right: "}"}
  - {t: F, right: "="}
  - {t: L, right: "\\"}
  - {t: R, h: "⌃", right: "+"}
  - {t: T, h: "⌘", right: "-"}
  - {t: I, h: "⌥", right: "/"}
  - {t: U, h: "⇧", right: '"'}
  - {t: Z, right: "~"}
  - {t: X, right: "["}
  - {t: "-", s: "?", right: "]"}
  - {t: V, right: "_"}
  - {t: B, right: "#"}
  - {t: ".", s: ":", right: "|"}
  - {t: H, right: "!"}
  - {t: G, right: ";"}
  - {t: ",", s: ";", right: ":"}
  - {t: K, right: "?"}
  - ⎋
  - {t: ⌫, h: left}
  - {t: ␣, h: right}
  - ↩
  right:
  - ''
  - "⇱"
  - "↑"
  - "⇲"
  - "⇞"
  - "/"
  - '7'
  - '8'
  - '9'
  - ''
  - {t: "↹", h: "⇧"}
  - {t: "←", h: "⌥"}
  - {t: "↓", h: "⌘"}
  - {t: "→", h: "⌃"}
  - "⇟"
  - "-"
  - {t: '4', h: "⌃"}
  - {t: '5', h: "⌘"}
  - {t: '6', h: "⌥"}
  - {t: '0', h: "⇧"}
  - ''
  - VOL DN
  - MUTE
  - VOL UP
  - ''
  - ","
  - '1'
  - '2'
  - '3'
  - "."
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  left:
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - F7
  - F8
  - F9
  - F10
  - {t: ↹, h: "⇧"}
  - "⌥"
  - "⌘"
  - "⌃"
  - ⌘R
  - ''
  - "⌃"
  - "⌘"
  - "⌥"
  - {t: F11, h: "⇧"}
  - ''
  - ⌘1
  - ⌘4
  - ⌘⇧4
  - ''
  - ''
  - ''
  - ''
  - ''
  - F12
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  tri:
  - '&sys_reset'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - BT 0
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&sys_reset'
  - '&bootloader'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - BT 1
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&bootloader'
  - '&studio_unlock'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - BT CLR
  - BT 2
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&studio_unlock'
  - {t: ▽, type: trans}
  - {type: held}
  - {type: held}
  - {t: ▽, type: trans}
